project:
  type: book

book:
  title: "TOPFUN Project Documentation"
  author: "Radim Hlad√≠k"
  date: today
  chapters:
    - index.qmd
    - part: "Subprojects orchestration via main file"
    - _main.qmd
    - part: "Subprojects"
    - _data_api.qmd
    - _data_get.qmd
    - _data_process.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



